# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XHRRLsbyK69RZBx_l-928GgDDwPumoFI
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("wildlife_conservation.csv")

print("Dataset Loaded Successfully")
print("First Rows:")
print(df.head())
print("Columns:")
print(df.columns)

import matplotlib.pyplot as plt
import seaborn as sns

# Population trend by Year
plt.figure(figsize=(10,5))
sns.lineplot(data=df, x="Year", y="Population", hue="Species", marker="o")
plt.title("Population Trend by Species")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(data=df, x="Conservation_status", palette="Set2")
plt.title("Conservation Status Distribution")
plt.xticks(rotation=30)
plt.show()

